version: '3.8'

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=111111222
      - POSTGRES_DB=phonebook
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5442:5432
